// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: markfeedfetched.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const markFeedFetched = `-- name: MarkFeedFetched :one
UPDATE feeds
SET updated_at = $1,
 last_fetched_at = $2
RETURNING id, created_at, updated_at, name, url, user_id, last_fetched_at
`

type MarkFeedFetchedParams struct {
	UpdatedAt     time.Time
	LastFetchedAt sql.NullTime
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, markFeedFetched, arg.UpdatedAt, arg.LastFetchedAt)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
